### ISSUE TITLE
Find out a viable import pipeline from an osm or pbf or o5m

### ISSUE THREAD

**Issue by kpanic** [kpanic/pollicino#5]
**Description**
Currently a `CSV` file is generated with the `osmfilter`/`osmconvert` commands, which brings problems because the result CSV fields are not wrapped and the content is not escaped.

**Current status**
The current workflow is:

```
osmfilter --keep="highway=residential =primary =secondary =tertiaty =unclassified addr:suburb= addr:city= addr:street= addr:housenumber= addr:postcode= addr:full=" anopenstreetmapfile.osm > 
filtered-openstreemapfile.osm
```

```
echo "street,housenumber,postcode,suburb,city,lon,lat,full">germany-streets.csv
osmconvert --all-to-nodes --csv="addr:street addr:housenumber addr:postcode addr:suburb addr:city @lon @lat addr:full" --csv-separator=, --max-objects=99000000 filtered-openstreetmapfile.osm >> streets.csv
```

Which works but it has the aforementioned problem.

**Scope**
Find out a better pipeline to extract data from an `.osm` or `.pbf` or `.o5m` and index it in our storage

**Comment by missinglink** [comment]
hey @kpanic I wrote this util which is nice and fast streaming parser for extracting from `.pbf` files https://github.com/pelias/pbf2json it also handles denormalizing the data for you, which is really super helpful if you are not using a relational database.

It supports the same sort of filtering methods as `osmconvert` does with the `~` delimiter also added recently, it's well tested and we use it in production to parse the 25GB planet file regularly.

this may also be of interest to you:
https://github.com/pelias/pbf-parser-comparison

**Comment by kpanic** [comment]
@missinglink awesome, I will try it out soon! Thank you very much

**Comment by kpanic** [comment]
Closing this issue since pbf2json fits perfectly the need.
Addressed the issue in commit https://github.com/kpanic/pollicino/commit/e4f081c21061afcae37db8daacbea639372c1d26
Thanks again @missinglink !

**Comment by missinglink** [comment]
no problem, I merged the centroid calculations code now too, so the latest version will give you way centroids for free.
